"""Markdown export — GitHub-flavored, signing-friendly."""

from __future__ import annotations

from io import StringIO

from wimsalabim.core.schema import ScanReport


def render_markdown(report: ScanReport) -> str:
    out = StringIO()
    out.write(f"# wimsalabim scan · `{report.target}`\n\n")
    out.write(
        f"- **target**: `{report.target}`\n"
        f"- **schema**: `{report.schema_version}`\n"
        f"- **tool**: `wimsalabim/{report.tool_version}`\n"
        f"- **started**: `{report.started_at.isoformat()}`\n"
        f"- **duration**: `{report.duration_ms:.0f} ms`\n"
        f"- **config-hash**: `{report.config_hash}`\n"
    )
    if report.authorization:
        out.write(
            f"- **authorization**: `{report.authorization.mode}` "
            f"(verified `{report.authorization.verified_at.isoformat()}`)\n"
        )
    if report.signature:
        out.write(f"- **signature**: `{report.signature[:32]}…` (Ed25519)\n")
    out.write("\n---\n\n")

    if report.risk:
        risk = report.risk
        out.write(f"## Risk · grade `{risk.grade}` · score `{risk.overall_score:.1f}/100`\n\n")
        out.write(f"> {risk.summary}\n\n")
        if risk.rules_fired:
            out.write("| Rule | Severity | Points | Rationale |\n")
            out.write("|------|----------|--------|-----------|\n")
            for hit in risk.rules_fired:
                out.write(
                    f"| `{hit.rule_id}` | {hit.severity} | {hit.points:.0f} | {hit.rationale} |\n"
                )
            out.write("\n")

    out.write("## Analyzers\n\n")
    for name in sorted(report.analyzers):
        result = report.analyzers[name]
        out.write(f"### `{name}` · {result.status}\n\n")
        if result.status != "ok" or result.report is None:
            reason = result.skip_reason or result.error_message or "(no detail)"
            out.write(f"> {reason}\n\n")
            continue
        rep = result.report
        out.write(
            f"- **grade**: `{rep.grade}`\n"
            f"- **duration**: {rep.duration_ms:.0f} ms\n"
            f"- **findings**: {len(rep.findings)}\n\n"
        )
        if rep.metadata:
            out.write("<details><summary>Metadata</summary>\n\n")
            for k, v in sorted(rep.metadata.items()):
                out.write(f"- `{k}` → `{v}`\n")
            out.write("\n</details>\n\n")
        if rep.findings:
            out.write("| Severity | ID | Title | CWE |\n")
            out.write("|----------|----|-------|-----|\n")
            for f in rep.findings:
                cwe = f.cwe or "—"
                out.write(f"| {f.severity} | `{f.id}` | {f.title} | {cwe} |\n")
            out.write("\n")

    out.write("---\n\n_Generated by wimsalabim under PVNL flag._\n")
    return out.getvalue()


__all__ = ["render_markdown"]
